# Generated by Django 5.1.3 on 2024-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="plus_ones",
            new_name="number_of_companions",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="phone",
        ),
        migrations.AlterField(
            model_name="guest",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="guest",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
