# Generated by Django 5.1.3 on 2024-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0003_alter_guest_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="email",
        ),
        migrations.AddField(
            model_name="guest",
            name="court",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="row",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
